services:
  xkiosk-imx8:
    image: hub.foundries.io/arduino/x-kiosk-imx8@sha256:b13623595bc516f67f04d59d2e69e41c88a01bbc967bbfe6f5fc43aab36cd5b0
    restart: unless-stopped
    tty: true
    command: "https://mcmchris.com"
    #command: "--kiosk --no-first-run --incognito www.foundries.io}"
    read_only: true
    network_mode: "host"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /run/user/63:/run/user/63
    - /dev/dri:/dev/dri
    - /dev/galcore:/dev/galcore
    device_cgroup_rules:
    - 'c 199:* rmw'
    - 'c 226:* rmw'